spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}