spring:
  application:
    name: spring-docker-template

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  profiles:
    active: dev

server:
  port: ${SERVER_PORT:8081}